name: End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # and run all Cypress tests
      - name: Cypress run
        # Install npm dependencies, cache them correctly

        uses: cypress-io/github-action@v6
        with:
          command: npm run grep-test


      - name: Cypress mochaawesome Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
         name: Moacha
         path: cypress/reports/html
      
          